#!/usr/bin/env bash

# Installing HAProxy version 2.0
sudo apt-get install --no-install-recommends -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.real.cfg

sudo cat <<EOF >> /etc/haproxy/haproxy.cfg

frontend http
    bind *:80
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 490730-web-01 18.210.19.150:80 check
    server 490730-web-02 34.224.62.244:80 check
EOF

# Restart HAProxy service
sudo systemctl restart haproxy

# Enabling init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy
