#!/usr/bin/env bash
# installing a load balancer and configuring the HAProxy to send traffic
# to web-01 and web-02

#installing HAProxy version 2.8
sudo apt-get install --no-install-recommends -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get install -y haproxy=2.8.\*

# Configure HAProxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

STUDENT_ID=490730
SERVER1_IP='18.210.19.150'
SERVER2_IP='34.224.62.244'

cat <<EOF >> /etc/haproxy/haproxy.cfg
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server ${STUDENT_ID}-web-01 $SERVER1_IP check
    server ${STUDENT_ID}-web-02 $SERVER2_IP check
EOF

# Restart HAProxy service
service haproxy restart

#!/usr/bin/env bash
# Installs and configures HAProxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get install -y haproxy=2.8.\*

# Enabling init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Creating a copy of HAProxy's config file

# configuring to load balance web1 and web2 servers
echo "
	frontend myfrontend
		bind *:80
		option httpclose
		option httplog
		option forwardfor
		default_backend mybackend
	backend mybackend
		mode http
		balance roundrobin
		server 190195-web-01 54.157.134.178:80 check
		server 190195-web-02 34.229.161.255:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy start
