#!/usr/bin/env bash
# Installing HAProxy version 2.8
sudo apt-get install --no-install-recommends -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install -y haproxy=2.8.\*

# Backup HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

# Configure HAProxy
STUDENT_ID=490730
SERVER1_IP='18.210.19.150'
SERVER2_IP='34.224.62.244'

cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server ${STUDENT_ID}-web-01 $SERVER1_IP check
    server ${STUDENT_ID}-web-02 $SERVER2_IP check
EOF

# Verify HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart
