#!/usr/bin/env bash
# a bash script that configures nginx to run as nginx user instead of root

sudo adduser nginx
sudo chown -R nginx /var/log/nginx /var/lib/nginx
sudo sed -i s/root/nginx/g /etc/nginx/nginx.conf
sudo nginx -t
sudo systemctl restart nginx
